# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0002_auto_20161031_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 3, 17, 34, 280027)),
        ),
        migrations.AddField(
            model_name='user',
            name='user_skills',
            field=models.ManyToManyField(to='userList.Skill'),
        ),
    ]
