# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0004_auto_20161031_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 10, 31, 23, 22, 24, 112712, tzinfo=utc)),
        ),
    ]
