# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0005_auto_20161031_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 23, 25, 25, 58675, tzinfo=utc)),
        ),
    ]
